### ISSUE TITLE
Link to included template with <cfinclude> is broken

### ISSUE THREAD

**Issue by eescovar** [cfmleditor/cfmleditor#15]
Hello,

It seems that last updates have broken the feature of showing a link to a included template using < cfinclude > tag.

Furthermore, I've noticed that the CHANGELOG.md file has not been updated for a while. 
Whereas last version is v0.6.19, the changelog shows v.0.6.12 as the last one.

**Comment by ghedwards** [comment]
Damn, really ? I fixed this recently, perhaps something with the new file type has broken it, will have a look tomorrow

**Comment by eescovar** [comment]
`<cfinclude template="file.cfm">` does not show a link to "file.cfm".
(I am not using cfscript).

**Comment by ghedwards** [comment]
In a .cfm template?

**Comment by eescovar** [comment]
Yes. A simple .cfm template including another one.

Just checked that last working version for me was 0.6.14.

**Comment by ghedwards** [comment]
I wonder if a .CFS file is required to activate parts of the plugin now, I'll have to investigate further, because it seems to work ok for me

**Comment by eescovar** [comment]
Ok, I understand. I will have a try with a .CFS file and see if it works on 0.6.19.

**Comment by ghedwards** [comment]
Otherwise are there some more specifics you could help me identify? Are there any errors in debug output ? Specific template paths that don't work and those that do ? Do you use a workspace or individual directories?

**Comment by ghedwards** [comment]
I had someone let me know it was broken recently, but I think I resolved it for them

**Comment by eescovar** [comment]
All template paths don't work for me. They stopped working since v0.6.15.

**Comment by ghedwards** [comment]
<img width="501" alt="image" src="https://github.com/cfmleditor/cfmleditor/assets/125586/1b772bbf-c51a-4833-94ae-bb6d04c0dd8d">
try uninstalling / reinstalling or possibly look for conflicting extensions ? do you know anyone else using the extension that might be able to help determine if its something environmental ? I'm on a Mac, are you on windows ? that could play a factor ? Sorry I don't have time to diagnose this at the moment, perhaps pull the project and see if you can work out why its not working ?

**Comment by eescovar** [comment]
I've just tried uninstalling/reinstalling, without any luck.
I am on Windows. I have colleagues who also are experimenting this issue, although we use almost the same set of extensions.

Thanks for your effort. I will try to debug or detect conflicts with other extensions.

**Comment by ghedwards** [comment]
@eescovar I haven't given up, just a bit busy at the moment and its difficult when you cant reproduce something, have you tried vscode.dev to see if it works there ? it could have something to do with relative paths and the correct path separator or maybe case ?, I might check with other members of our team at work who are on windows. Also, I found this https://github.com/microsoft/vscode/issues/108256

**Comment by eescovar** [comment]
Thanks, I really appreciate that. 
Tried now on vscode.dev (great suggestion, btw). I've installed only CFML Editor. Same problem.

**Comment by ghedwards** [comment]
@eescovar I've managed to see this first hand, and it appears this is broken on windows, I'm going to try source a windows machine or VM so I can try debug the cause and fix it. Might be a week or two away though, any contributions would be welcome.

**Comment by eescovar** [comment]
Ok! I just want to emphasize that it works on v0.6.14 (v0.6.15 has broken it).

**Comment by ghedwards** [comment]
@eescovar sorry a colleague seems to think its working on windows in v0.6.19 but that it can take a few seconds to appear, please reach out on cfml slack if you can?

**Comment by ghedwards** [comment]
@eescovar there could be some kind of conflict occurring with the old cflint extension, please ensure you're using the associated cfmleditor one.

<img width="479" alt="image" src="https://github.com/cfmleditor/cfmleditor/assets/125586/0bb54797-3120-48c7-b815-2049173f9459">

**Comment by ghedwards** [comment]
Pushed some updates that might help

**Comment by eescovar** [comment]
Sorry for the late response.

Just tried uninstalling all CFML Editor versions, then restared vscode, and then reinstalled v0.6.20.
Failed. :-(

Rolled back to v0.6.14, links work as expected.

I guess it is something related to the Windows OS that got broken since v0.6.15.

**Comment by ghedwards** [comment]
@eescovar a colleague had a similar issue but was running the old cflint extension, uninstalled it and installed cfmleditor-lint and it fixed the issue, could you check this isn't a similar problem for you ?

**Comment by eescovar** [comment]
I didn't have the old cflint extension installed.
Just in case, I have installed cfmleditor-lint to check if this makes links work again. No luck.
For now, me and my colleagues will stay with v0.6.14, because we appreciate the link feature.

**Comment by ghedwards** [comment]
@eescovar v0.6.21 should fix this issue, finally got access to a windows laptop where I was able to replicate the issue, please let me know.

**Comment by eescovar** [comment]
Issue fixed, @ghedwards! Thank you very much!
