### ISSUE TITLE
Change log fell behind

### ISSUE THREAD

**Issue by bendur** [cfmleditor/cfmleditor#22]
I see there have been quite a few changes this year but [CHANGELOG.md](https://github.com/cfmleditor/cfmleditor/blob/master/CHANGELOG.md) only goes to version 0.6.12.

**Comment by garethedwards-tass** [comment]
@bendur would you like to help me with this ?

**Comment by ghedwards** [comment]
@bendur would you like to help me with this ?

**Comment by bendur** [comment]
@ghedwards how would you recommend gathering the change log? Do you have something written down, or would it be best to just go through pull requests/commits?

**Comment by ghedwards** [comment]
@bendur best to just go through pull requests/commits I think

**Comment by bendur** [comment]
Closing this, re: https://github.com/cfmleditor/cfmleditor/pull/24

**Comment by bendur** [comment]
Closing this, re: https://github.com/cfmleditor/cfmleditor/pull/24
