### ISSUE TITLE
all comments now default to javascript type no matter what

### ISSUE THREAD

**Issue by shanemcmurray** [cfmleditor/cfmleditor#23]
after recent update all comments default to javascript type: /* or // with  the normal keyboard command. I have a mix of HTML, javascript and cfml on any given page... but all comments are now javascript no matter what code it is.

is this an issue with a recent update? or something else that I can fix, I can't seem to find a way to resolve everything on the keyboard short cuts looks correct.

**Comment by ghedwards** [comment]
Can you provide an isolated example / test case of this occurring ?

**Comment by shanemcmurray** [comment]
Yeah check out this attached video example... javascript, cfml, and HTML... all use javascript comments on each one for the keyboard combination of: shift + alt + a

Here are the versions of my VS Code and CFML Editor extension:

More Info
Published
2023-12-12, 04:17:02
Last released
2024-07-04, 22:15:12
Last updated
2024-07-05, 08:03:08
Identifier
cfmleditor.cfmleditor

VSC
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631


https://github.com/user-attachments/assets/eb516fba-cf95-49cc-8444-197e2d5bdd97

**Comment by ghedwards** [comment]
@shanemcmurray I haven't changed anything in this space recently so it could be something that the parser is misunderstanding with a particular file that has a lot of javascript in it as well ? if you're able to create an isolated code example I might be able to take a look at it, otherwise unfortunately its going to be like finding a needle in a haystack, though you're already welcome to contribute a fix.

**Comment by shanemcmurray** [comment]
Well, I did a couple of things and it magically started working... its been like this for a week now... was driving me nuts... 

I did this to re-setup the shortcuts: 

https://stackoverflow.com/questions/66114434/commenting-out-code-does-not-work-properly-in-vs-code

that didn't work, so I did this to try and get some debug output:

https://github.com/microsoft/vscode/issues/210778

after that, I did a single line comment ctrl + /  and it worked normally on cfml...  so then I tried a block comment shift + alt + a and that worked... 

so no idea what fixed it.... but it it seems to be working now.
