### ISSUE TITLE
JavaScript optional chaining operator “?.” causes syntax highlighting to mess up

### ISSUE THREAD

**Issue by JonathanWilkins1** [cfmleditor/cfmleditor#33]
I noticed twice now that whenever I use the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), the syntax highlighting turns all the JS code (inside a script tag) blue. It eventually fixes itself after a bunch more lines of code, but I’m not sure what exactly causes it to fix itself. Attached is a screenshot of where the messed up syntax highlighting starts after using ?.

![image](https://github.com/user-attachments/assets/1502c731-1a15-46ee-8380-ad83acd80ebb)

**Comment by ghedwards** [comment]
Gave it a look but no luck tmLanguage files are like fine art, still considering a switch to tree sitter colouring

**Comment by burncitiesburn** [comment]
This potentially might be fix.
This is very lightly tested.

I found that adding ":" next to the use of the `?.` operator fixed the parsing which lead me to looking at the ternary parser.

These are changes to the `syntaxes/cfml.tmLanguage.json` file

![Screenshot 2024-11-28 at 12 15 31 PM](https://github.com/user-attachments/assets/5e68e288-c571-4d12-9790-db07945f509f)
![Screenshot 2024-11-28 at 12 15 25 PM](https://github.com/user-attachments/assets/08c9a4c2-8812-4df6-b14e-5a97bc7ec65a)

Testing:


Before:
![Screenshot 2024-11-28 at 12 17 23 PM](https://github.com/user-attachments/assets/81ce3523-e411-49e7-9f9c-dda8ec8c434f)


After:
![Screenshot 2024-11-28 at 12 21 08 PM](https://github.com/user-attachments/assets/7137e068-88aa-4b75-8099-ecc8529fc442)



I can push a PR with the change

**Comment by ghedwards** [comment]
Negative look ahead? Looks good. Yes please submit a PR

**Comment by ghedwards** [comment]
@burncitiesburn trouble with the PR ? I can push this change if you're unable to

**Comment by ghedwards** [comment]
Fixed in v0.6.30
